---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zot
  namespace: flux-system
spec:
  chart:
    spec:
      chart: zot
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: project-zot
      version: 0.1.32
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: zot
  values:
    configFiles:
      config.json: |-
        {
          "storage": {
            "subPaths":{
              "/dedup":{
                "rootDirectory": "/tmp/dedup",
                "dedupe": true,
                "gc": true,
                "storageDriver": {
                  "name": "s3",
                  "rootdirectory": "/dedup",
                  "region": "us-east-2",
                  "bucket": "zot-storage",
                  "accesskey": "minioadmin",
                  "secretkey": "minioadmin",
                  "regionendpoint": "http://minio.minio-dev.svc.cluster.local:9000",
                  "secure": false,
                  "skipverify": false
                }
              }
            },
            "storageDriver": {
              "name": "s3",
              "rootdirectory": "/zot",
              "region": "us-east-2",
              "bucket": "zot-storage",
              "accesskey": "minioadmin",
              "secretkey": "minioadmin",
              "regionendpoint": "http://minio.minio-dev.svc.cluster.local:9000",
              "secure": false,
              "skipverify": false
            },
            "rootDirectory": "/tmp/zot",
            "gc": true
          },
         "http": {
           "address": "0.0.0.0",
           "port": "5000",
           "auth": { "htpasswd": { "path": "/secret/htpasswd" } },
           "accessControl": {
             "repositories": {
               "**": {
                 "policies": [{
                   "users": ["user"],
                   "actions": ["read"]
                 }, {
                   "users": ["admin"],
                   "actions": ["create", "read", "update", "delete"]
                 }],
                 "anonymousPolicy": ["create", "read", "update", "delete"],
                 "defaultPolicy": ["create", "read", "update", "delete"]
               }
             },
             "adminPolicy": {
               "users": ["admin"],
               "actions": ["read", "create", "update", "delete"]
             }
           }
         },
          "log": { "level": "debug" }
        }
    mountConfig: true
    mountSecret: true
