apiVersion: v1
data:
  values.yaml: |
    components:
      frontend:
        resources:
          limits:
            memory: 210Mi
kind: ConfigMap
metadata:
  name: otel-demo-frontend
  namespace: flux-system
