---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: otel-demo
  namespace: flux-system
spec:
  chart:
    spec:
      chart: opentelemetry-demo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
      version: 0.27.0
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: otel-demo
